export const levelsList = [
    {
        level: 0,
        title: 'Type Selector',
        history: `You're about to learn CSS Selectors!
            Selectors are how you pick which element to apply styles to.
             Select to apply styles to every <div> element.
              You can do this with the selector div.
             This is called a type selector.
             What selector will select all <white> buns elements?`,
        tag: 'white',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: [],
        childSecond: [],
        childThird: [],
        childFourth: [],
        childFifth: [],
    },
    {
        level: 1,
        title: 'Type Selector',
        history: 'What selector will select all <black> buns elements?',
        tag: 'black',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: [],
        childSecond: [],
        childThird: [],
        childFourth: [],
        childFifth: [],
    },
    {
        level: 2,
        title: 'ID Selector',
        history: 'Selects the element with a specific #id',
        tag: '#select',
        id: 'select',
        html: ['black', 'white', 'black', 'white'],
        childFist: [],
        childSecond: [],
        childThird: [],
        childFourth: [],
        childFifth: [],
    },
    {
        level: 3,
        title: 'Type Selector',
        history: 'Select an element inside another element. What selector will select all <meat> elements?',
        tag: 'meat',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: ['meat', 'meat', 'meat', 'meat'],
        childSecond: [],
        childThird: [],
        childFourth: [],
        childFifth: [],
    },

    {
        level: 4,
        title: 'Descendant Selector',
        history:
            'Select an element inside another element. You can use a descendant combinator, which is simply a space, to combine the buns (<white>/<black>) selector with the <meat> selector to achieve this.',
        tag: 'white meat',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: ['meat', 'meat', 'meat', 'meat'],
        childSecond: [],
        childThird: [],
        childFourth: [],
        childFifth: [],
    },
    {
        level: 5,
        title: 'Class Selector',
        history:
            'Select elements by their class ".classname" The class selector selects all elements with that class attribute. Elements can only have one ID, but many classes.',
        tag: '.slice',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: ['meat', 'meat', 'meat', 'meat'],
        childSecond: ['cheese', 'cheese', 'cheese', 'cheese'],
        childThird: [],
        childFourth: [],
        childFifth: [],
    },

    {
        level: 6,
        title: 'Combine the Class Selector',
        history:
            'You can combine the class selector with other selectors, like the type selector. For example, select cheese with tomatoes.',
        tag: '.slice .tomato',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: ['meat', 'meat', 'meat', 'meat'],
        childSecond: ['cheese', 'cheese', 'cheese', 'cheese'],
        childThird: ['tomat', 'tomat', 'tomat', 'tomat'],
        childFourth: [],
        childFifth: [],
    },

    {
        level: 7,
        title: 'Combine the Tag Selector and ID',
        history: 'You have to select white buns, but one of buns choose salat with id selector',
        tag: 'white #select_salat',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: ['meat', 'meat', 'meat', 'meat'],
        childSecond: ['cheese', 'cheese', 'cheese', 'cheese'],
        childThird: ['tomat', 'tomat', 'tomat', 'tomat'],
        childFourth: ['salat', 'salat', 'salat', 'salat'],
        childFifth: [],
    },
    {
        level: 8,
        title: 'Comma Combinator',
        history:
            'Combine, selectors, with... commas! You can combine any selectors this way, and you can specify more than two. Select cheese, tomato and salat.',
        tag: 'cheese, .tomato, salat',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: ['meat', 'meat', 'meat', 'meat'],
        childSecond: ['cheese', 'cheese', 'cheese', 'cheese'],
        childThird: ['tomat', 'tomat', 'tomat', 'tomat'],
        childFourth: ['salat', 'salat', 'salat', 'salat'],
        childFifth: [],
    },
    {
        level: 9,
        title: 'Combine the skills  :)',
        history: `Let's selected only black hamburgers.`,
        tag: '.my__order',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: ['meat', 'meat', 'meat', 'meat'],
        childSecond: ['cheese', 'cheese', 'cheese', 'cheese'],
        childThird: ['tomat', 'tomat', 'tomat', 'tomat'],
        childFourth: ['salat', 'salat', 'salat', 'salat'],
        childFifth: ['black', 'white', 'black', 'white'],
    },
    {
        level: 10,
        title: 'Select all!',
        history:
            'The Universal Selector! You can select everything! You can select all elements with the universal selector * !',
        tag: '*',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        childFist: ['meat', 'meat', 'meat', 'meat'],
        childSecond: ['cheese', 'cheese', 'cheese', 'cheese'],
        childThird: ['tomat', 'tomat', 'tomat', 'tomat'],
        childFourth: ['salat', 'salat', 'salat', 'salat'],
        childFifth: ['black', 'white', 'black', 'white'],
    },
];
