export const levelsList = [
    {
        level: 0,
        title: 'Type Selector',
        history: `You're about to learn CSS Selectors!
            Selectors are how you pick which element to apply styles to.
             Select to apply styles to every <div> element.
              You can do this with the selector div.
             This is called a type selector.
             What selector will select all white buns elements?`,
        help: '***ПОМОЖИТЕ***',
        tag: 'white',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        child: [],
    },
    {
        level: 1,
        title: 'Type Selector',
        history: 'What selector will select all black buns elements?',
        help: '***ПОМОЖИТЕ***',
        tag: 'black',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        child: [],
    },
    {
        level: 2,
        title: 'ID Selector',
        history: 'Selects the element with a specific #id',
        help: '***ПОМОЖИТЕ***',
        tag: '#select',
        id: 'select',
        html: ['black', 'white', 'black', 'white'],
        child: [],
    },
    {
        level: 3,
        title: 'Descendant Selector',
        history:
            'Select an element inside another element. You can use a descendant combinator, which is simply a space, to combine the buns (white/black) selector with the meet selector to achieve this.',
        help: '***ПОМОЖИТЕ***',
        tag: 'white meet',
        id: '',
        html: ['black', 'white', 'black', 'white'],
        child: ['white', 'meet'],
    },

    {
        level: 4,
        title: '',
        history: '',
        help: '',
        tag: '',
        id: '',
        html: [],
        child: [],
    },
    {
        level: 5,
        title: '',
        history: '',
        help: '',
        tag: '',
        id: '',
        html: [],
        child: [],
    },

    {
        level: 6,
        title: '',
        history: '',
        help: '',
        tag: '',
        id: '',
        html: [],
        child: [],
    },

    {
        level: 7,
        title: '',
        history: '',
        help: '',
        tag: '',
        id: '',
        html: [],
        child: [],
    },
    {
        level: 8,
        title: '',
        history: '',
        help: '',
        tag: '',
        id: '',
        html: [],
        child: [],
    },
    {
        level: 9,
        title: '',
        history: '',
        help: '',
        tag: '',
        id: '',
        html: [],
        child: [],
    },
    {
        level: 10,
        title: 'Select all the things!',
        history:
            'The Universal Selector! You can select everything! You can select all elements with the universal selector * !',
        help: '***ПОМОЖИТЕ***',
        tag: '*',
        id: '',
        html: [],
        child: [],
    },
];
